version: '3.9'

services:
  reviews-database:
    image: mongo
    ports:
      - "27017:27017"
    
  reviews-backend:
    build: ./backend
    environment:
      - DATABASE_URL=mongodb://reviews-database:27017/reviews
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - reviews-database
    
  reviews-frontend:
    build: .
    environment:
      - VITE_BACKEND_URL=http://reviews-backend:3001/api/v1
    ports:
      - "3000:80"
    depends_on:
      - reviews-backend
  

